/**
 * Sinhronizuje ceo katalog sa Tabela Cene.xlsx (kolona C + maloprodajna).
 * - Cene i broj artikla po LEON šifri (leon-site-sku-cache) kad postoji
 * - Generiše excel-shop-slugs.json
 *
 * npx tsx scripts/sync-excel-shop-from-sheet.ts
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Product } from '../data/products';
import { products } from '../data/products';
import { harborMensSandalProducts } from '../data/harbor-mens-sandals';
import { leonProducts } from '../data/leon-products.generated';
import {
  excelPricedProductSlugs,
  findExcelRowForProduct,
  matchProductsForExcelRow,
  type ExcelPriceRow,
} from '../src/lib/excelCatalogMatch';

const EXCEL_PATH = String.raw`D:\Cursor_AI\Sima sajt dokumenti\Tabela Cene.xlsx`;
const OUT_TS = join(__dirname, '../data/leon-products.generated.ts');
const OUT_HARBOR = join(__dirname, '../data/harbor-mens-sandals.ts');
const OUT_SLUGS = join(__dirname, '../data/excel-shop-slugs.json');

function loadExcel(): ExcelPriceRow[] {
  const py = join(__dirname, 'read-excel-prices.py');
  const raw = execSync(`python "${py}" "${EXCEL_PATH}"`, { encoding: 'utf8' });
  return (JSON.parse(raw) as ExcelPriceRow[]).filter(
    (r) => r.naziv && Number.isFinite(r.maloprodajna)
  );
}

function colorFromName(name: string): string | null {
  const parts = name.split(/\s*[–—-]\s*/);
  if (parts.length < 2) return null;
  const tail = parts[parts.length - 1].trim();
  return tail.length ? tail : null;
}

const excel = loadExcel();
const leonList = leonProducts as unknown as Product[];
const harborList = harborMensSandalProducts as Product[];

function applyExcelToCatalog(catalog: Product[], label: string) {
  let priced = 0;
  let cleared = 0;
  for (const p of catalog) {
    const row = findExcelRowForProduct(p, excel);
    const color = colorFromName(p.name.en) ?? colorFromName(p.name.de);

    if (row) {
      p.articleNumber = row.broj;
      for (const v of p.variants) v.priceCHF = row.maloprodajna;
      priced++;
    } else {
      for (const v of p.variants) v.priceCHF = null;
      cleared++;
    }

    if (color) p.colorLabel = color;
  }
  console.log(`${label}: Excel cena ${priced}, bez cene ${cleared}`);
}

applyExcelToCatalog(leonList, 'Leon');
applyExcelToCatalog(harborList, 'Harbor');

writeFileSync(
  OUT_TS,
  `/* AUTO-GENERATED by scripts/leon-scrape-explore.mjs + excel sync */\n` +
    `export const leonProducts = ${JSON.stringify(leonList, null, 2)};\n`,
  'utf8'
);

let harborSrc = readFileSync(OUT_HARBOR, 'utf8');
const harborPrice =
  harborList.find((p) => p.variants[0]?.priceCHF != null)?.variants[0]?.priceCHF ?? null;
if (harborPrice != null) {
  harborSrc = harborSrc.replace(/const priceCHF = [\d.]+;/, `const priceCHF = ${harborPrice};`);
  writeFileSync(OUT_HARBOR, harborSrc, 'utf8');
}

const slugs = excelPricedProductSlugs(products, excel);
writeFileSync(OUT_SLUGS, JSON.stringify(slugs, null, 2) + '\n', 'utf8');

const unmatched = excel.filter((row) => matchProductsForExcelRow(row, products).length === 0);

console.log('Excel redova:', excel.length);
console.log('Shop slugova (ceo katalog):', slugs.length);
console.log('Excel redovi bez matcha u katalogu:', unmatched.length);
if (unmatched.length) {
  for (const r of unmatched) console.log(`  - ${r.broj} ${r.naziv} (${r.maloprodajna} CHF)`);
}

const aurora = leonList.filter((p) => p.slug.startsWith('aurora-v-'));
for (const p of aurora) {
  const price = p.variants[0]?.priceCHF;
  console.log(`  ${p.slug} → art. ${p.articleNumber}, ${price} CHF`);
}
